package Tugas2;


import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MNasiGoreng = new javax.swing.JCheckBox();
        MNasiLalap = new javax.swing.JCheckBox();
        TotNasGor = new javax.swing.JTextField();
        MNasiPecel = new javax.swing.JCheckBox();
        MinJeruk = new javax.swing.JCheckBox();
        MinTeh = new javax.swing.JCheckBox();
        MinKelapa = new javax.swing.JCheckBox();
        QTYNasGor = new javax.swing.JTextField();
        TotNasPec = new javax.swing.JTextField();
        TotNasLap = new javax.swing.JTextField();
        TotJeruk = new javax.swing.JTextField();
        TotTeh = new javax.swing.JTextField();
        TotKelapa = new javax.swing.JTextField();
        HargaNasGor = new javax.swing.JTextField();
        HargaNasLap = new javax.swing.JTextField();
        HargaNasPec = new javax.swing.JTextField();
        HargaJeruk = new javax.swing.JTextField();
        HargaTeh = new javax.swing.JTextField();
        HargaKelapa = new javax.swing.JTextField();
        QTYNasLap = new javax.swing.JTextField();
        QTYNasPec = new javax.swing.JTextField();
        QTYJeruk = new javax.swing.JTextField();
        QTYTeh = new javax.swing.JTextField();
        QTYKelapa = new javax.swing.JTextField();
        RPromo = new javax.swing.JRadioButton();
        RNon = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        TotAkhir = new javax.swing.JTextField();
        BHitung = new javax.swing.JToggleButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(142, 157, 218));

        jPanel2.setBackground(new java.awt.Color(140, 137, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PENJUALAN MAKANAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Makanan/Minuman");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QTY");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total");

        MNasiGoreng.setBackground(new java.awt.Color(0, 0, 0));
        MNasiGoreng.setForeground(new java.awt.Color(255, 255, 255));
        MNasiGoreng.setText("Nasi Goreng");

        MNasiLalap.setBackground(new java.awt.Color(0, 0, 0));
        MNasiLalap.setForeground(new java.awt.Color(255, 255, 255));
        MNasiLalap.setText("Nasi Lalapan");

        TotNasGor.setEditable(false);
        TotNasGor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotNasGorMouseClicked(evt);
            }
        });

        MNasiPecel.setBackground(new java.awt.Color(0, 0, 0));
        MNasiPecel.setForeground(new java.awt.Color(255, 255, 255));
        MNasiPecel.setText("Nasi Pecel");

        MinJeruk.setBackground(new java.awt.Color(0, 0, 0));
        MinJeruk.setForeground(new java.awt.Color(255, 255, 255));
        MinJeruk.setText("Es Jeruk/ Jeruk Hangat");

        MinTeh.setBackground(new java.awt.Color(0, 0, 0));
        MinTeh.setForeground(new java.awt.Color(255, 255, 255));
        MinTeh.setText("Teh Hangat/Es Teh");

        MinKelapa.setBackground(new java.awt.Color(0, 0, 0));
        MinKelapa.setForeground(new java.awt.Color(255, 255, 255));
        MinKelapa.setText("Es Kelapa");

        QTYNasGor.setText("0");
        QTYNasGor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYNasGorMouseClicked(evt);
            }
        });

        TotNasPec.setEditable(false);
        TotNasPec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotNasPecMouseClicked(evt);
            }
        });

        TotNasLap.setEditable(false);
        TotNasLap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotNasLapMouseClicked(evt);
            }
        });

        TotJeruk.setEditable(false);
        TotJeruk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotJerukMouseClicked(evt);
            }
        });

        TotTeh.setEditable(false);
        TotTeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotTehMouseClicked(evt);
            }
        });

        TotKelapa.setEditable(false);
        TotKelapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotKelapaMouseClicked(evt);
            }
        });

        HargaNasGor.setText("10000");
        HargaNasGor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HargaNasGorMouseClicked(evt);
            }
        });

        HargaNasLap.setText("12000");

        HargaNasPec.setText("13000");

        HargaJeruk.setText("4000");

        HargaTeh.setText("3000");

        HargaKelapa.setText("5000");

        QTYNasLap.setText("0");
        QTYNasLap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYNasLapMouseClicked(evt);
            }
        });

        QTYNasPec.setText("0");
        QTYNasPec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYNasPecMouseClicked(evt);
            }
        });

        QTYJeruk.setText("0");

        QTYTeh.setText("0");
        QTYTeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYTehMouseClicked(evt);
            }
        });
        QTYTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QTYTehActionPerformed(evt);
            }
        });

        QTYKelapa.setText("0");
        QTYKelapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYKelapaMouseClicked(evt);
            }
        });

        buttonGroup1.add(RPromo);
        RPromo.setText("Promo");

        buttonGroup1.add(RNon);
        RNon.setText("NonPromo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOTAL AKHIR");

        TotAkhir.setEditable(false);
        TotAkhir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        BHitung.setText("Hitung");
        BHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(MNasiGoreng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MNasiLalap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MNasiPecel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MinJeruk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MinTeh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(MinKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QTYNasGor)
                            .addComponent(QTYNasLap)
                            .addComponent(QTYNasPec)
                            .addComponent(QTYJeruk)
                            .addComponent(QTYTeh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QTYKelapa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(RNon))
                    .addComponent(jLabel8))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(HargaNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TotNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HargaNasLap, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaNasPec, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotKelapa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TotTeh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TotNasPec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(TotNasLap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(TotJeruk, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BHitung))
                            .addComponent(TotAkhir))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MNasiGoreng)
                    .addComponent(TotNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QTYNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MNasiLalap)
                    .addComponent(TotNasLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaNasLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QTYNasLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MNasiPecel)
                    .addComponent(TotNasPec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaNasPec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QTYNasPec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinJeruk)
                    .addComponent(TotJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QTYJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinTeh)
                    .addComponent(TotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QTYTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinKelapa)
                    .addComponent(QTYKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RNon)
                            .addComponent(RPromo))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(TotAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BHitung)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotNasGorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotNasGorMouseClicked
        TotNasGor.setEditable(false);
    }//GEN-LAST:event_TotNasGorMouseClicked

    private void TotNasPecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotNasPecMouseClicked
        TotNasPec.setEditable(false);
    }//GEN-LAST:event_TotNasPecMouseClicked

    private void TotNasLapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotNasLapMouseClicked
        TotNasLap.setEditable(false);
    }//GEN-LAST:event_TotNasLapMouseClicked

    private void TotJerukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotJerukMouseClicked
        TotJeruk.setEditable(false);
    }//GEN-LAST:event_TotJerukMouseClicked

    private void TotTehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotTehMouseClicked
        TotTeh.setEditable(false);
    }//GEN-LAST:event_TotTehMouseClicked

    private void TotKelapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotKelapaMouseClicked
        TotKelapa.setEditable(false);
    }//GEN-LAST:event_TotKelapaMouseClicked

    private void HargaNasGorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HargaNasGorMouseClicked
        HargaNasGor.setEditable(false);
    }//GEN-LAST:event_HargaNasGorMouseClicked

    private void QTYNasGorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYNasGorMouseClicked
        QTYNasGor.setEditable(false);

        if(MNasiGoreng.isSelected()){
            QTYNasGor.setEditable(true);
        }
    }//GEN-LAST:event_QTYNasGorMouseClicked

    private void QTYNasLapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYNasLapMouseClicked
        QTYNasLap.setEditable(false);

        if(MNasiLalap.isSelected()){
            QTYNasLap.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_QTYNasLapMouseClicked

    private void QTYNasPecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYNasPecMouseClicked
        QTYNasPec.setEditable(false);

        if(MNasiPecel.isSelected()){
            QTYNasPec.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_QTYNasPecMouseClicked

    private void QTYTehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYTehMouseClicked
        QTYTeh.setEditable(false);

        if(MinTeh.isSelected()){
            QTYTeh.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_QTYTehMouseClicked

    private void QTYKelapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYKelapaMouseClicked
        QTYKelapa.setEditable(false);

        if(MinKelapa.isSelected()){
            QTYKelapa.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_QTYKelapaMouseClicked

    private void BHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHitungActionPerformed
        String NasGor=QTYNasGor.getText();
        String NasLap=QTYNasLap.getText();
        String NasPec=QTYNasPec.getText();
        String Jeruk= QTYJeruk.getText();
        String Teh = QTYTeh.getText();
        String Kelapa= QTYKelapa.getText();
        
        if(NasGor.equals("0") && NasLap.equals("0") && 
                NasPec.equals("0") && Jeruk.equals("0")
                && Teh.equals("0") && Kelapa.equals("0")){
            JOptionPane.showMessageDialog(null, "Isi QTYnya bro, Jangan Lupa Checklist barang yang dibeli");
        }
        
        try{
            int nasgor = Integer.parseInt(NasGor);
            int naslap= Integer.parseInt(NasLap);
            int naspec = Integer.parseInt(NasPec);
            int jeruk = Integer.parseInt(Jeruk);
            int teh = Integer. parseInt(Teh);
            int kelapa = Integer.parseInt(Kelapa);
            
            int total1=nasgor*10000;
            int total2=naslap*12000;
            int total3=naspec*13000;
            int total4=jeruk*4000;
            int total5=teh*3000;
            int total6=kelapa*5000;
            
            TotNasGor.setText(String.valueOf(total1));
            TotNasLap.setText(String.valueOf(total2));
            TotNasPec.setText(String.valueOf(total3));
            TotJeruk.setText(String.valueOf(total4));
            TotTeh.setText(String.valueOf(total5));
            TotKelapa.setText(String.valueOf(total6));
            
            if(RPromo.isSelected()){
                double totalAll=total1+total2+total3+total4+total5+total6;
                double promo=totalAll*0.1;
                totalAll=totalAll-promo;
                TotAkhir.setText(String.valueOf(totalAll));
            }else{
                int totalNon=total1+total2+total3+total4+total5+total6;
                TotAkhir.setText(String.valueOf(totalNon));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Isi QTY menggunakan angka saja");
        }
        
    }//GEN-LAST:event_BHitungActionPerformed

    private void QTYTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QTYTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QTYTehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        JOptionPane.showMessageDialog(null, "Welcome, program ini masih banyak bugnya jadi maafkanlah");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BHitung;
    private javax.swing.JTextField HargaJeruk;
    private javax.swing.JTextField HargaKelapa;
    private javax.swing.JTextField HargaNasGor;
    private javax.swing.JTextField HargaNasLap;
    private javax.swing.JTextField HargaNasPec;
    private javax.swing.JTextField HargaTeh;
    private javax.swing.JCheckBox MNasiGoreng;
    private javax.swing.JCheckBox MNasiLalap;
    private javax.swing.JCheckBox MNasiPecel;
    private javax.swing.JCheckBox MinJeruk;
    private javax.swing.JCheckBox MinKelapa;
    private javax.swing.JCheckBox MinTeh;
    private javax.swing.JTextField QTYJeruk;
    private javax.swing.JTextField QTYKelapa;
    private javax.swing.JTextField QTYNasGor;
    private javax.swing.JTextField QTYNasLap;
    private javax.swing.JTextField QTYNasPec;
    private javax.swing.JTextField QTYTeh;
    private javax.swing.JRadioButton RNon;
    private javax.swing.JRadioButton RPromo;
    private javax.swing.JTextField TotAkhir;
    private javax.swing.JTextField TotJeruk;
    private javax.swing.JTextField TotKelapa;
    private javax.swing.JTextField TotNasGor;
    private javax.swing.JTextField TotNasLap;
    private javax.swing.JTextField TotNasPec;
    private javax.swing.JTextField TotTeh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
